# Generated by Django 5.1.2 on 2024-11-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Rating')),
                ('location', models.CharField(choices=[('lanco', 'Lanco'), ('mariquina', 'Mariquina')], max_length=50, verbose_name='Location')),
                ('food_type', models.CharField(choices=[('sushi', 'Sushi'), ('carnes', 'Parrillas'), ('mar', 'Comida de mar'), ('pizza', 'Pizza'), ('pastas', 'Pastas'), ('hamburguesas', 'Hamburguesa'), ('postres', 'Postres'), ('desayunos', 'Desayunos')], max_length=50, verbose_name='Food Type')),
            ],
        ),
    ]
