# Generated by Django 5.1.2 on 2024-11-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Food Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='food_type',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='food_types',
            field=models.ManyToManyField(related_name='restaurantes', to='api.foodtype', verbose_name='Food Types'),
        ),
    ]
