# Generated by Django 5.1.2 on 2024-11-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_foodtype_remove_restaurante_food_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='exact_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Exact Location'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
    ]
