# Generated by Django 5.1.2 on 2024-11-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_restaurante_exact_location_restaurante_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Google Place ID'),
        ),
    ]
