# Generated by Django 5.1.2 on 2024-11-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurante_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/', verbose_name='Image'),
        ),
    ]
