# Generated by Django 5.1.2 on 2024-11-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_restaurante_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('ubicacion', models.CharField(choices=[('Lanco', 'Lanco'), ('Mariquina', 'Mariquina')], max_length=50, verbose_name='Ubicación')),
                ('motivo', models.CharField(choices=[('contacto', 'Contacto'), ('sugerencia', 'Sugerencia'), ('agregar_local', 'Agregar Local')], max_length=20, verbose_name='Motivo')),
                ('mensaje', models.TextField(max_length=1000, verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
            },
        ),
    ]
