# Generated by Django 5.1.2 on 2024-12-04 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_trafficrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrecord',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.restaurante'),
        ),
    ]
