# Generated by Django 5.1.2 on 2024-12-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dka3j5hvp/image/upload/v1/media/profile_pictures/default-profile.png', max_length=500, null=True, verbose_name='Profile Picture'),
        ),
    ]
