# Generated by Django 5.1.2 on 2024-12-10 19:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
